<a href="https://colab.research.google.com/github/soni113/Deployment-flask/blob/master/heart.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np
import pandas as pd

In [6]:
df = pd.read_csv('/spambase.csv')

In [7]:
df

         0  0.64  0.64.1  0.1  0.32   0.2  ...   0.43   0.44  3.756   61   278  1
0     0.21  0.28    0.50  0.0  0.14  0.28  ...  0.180  0.048  5.114  101  1028  1
1     0.06  0.00    0.71  0.0  1.23  0.19  ...  0.184  0.010  9.821  485  2259  1
2     0.00  0.00    0.00  0.0  0.63  0.00  ...  0.000  0.000  3.537   40   191  1
3     0.00  0.00    0.00  0.0  0.63  0.00  ...  0.000  0.000  3.537   40   191  1
4     0.00  0.00    0.00  0.0  1.85  0.00  ...  0.000  0.000  3.000   15    54  1
...    ...   ...     ...  ...   ...   ...  ...    ...    ...    ...  ...   ... ..
4595  0.31  0.00    0.62  0.0  0.00  0.31  ...  0.000  0.000  1.142    3    88  0
4596  0.00  0.00    0.00  0.0  0.00  0.00  ...  0.000  0.000  1.555    4    14  0
4597  0.30  0.00    0.30  0.0  0.00  0.00  ...  0.000  0.000  1.404    6   118  0
4598  0.96  0.00    0.00  0.0  0.32  0.00  ...  0.000  0.000  1.147    5    78  0
4599  0.00  0.00    0.65  0.0  0.00  0.00  ...  0.000  0.000  1.250    5    40  0

[4600 rows x 58 columns]

In [10]:
[row,col]=df.shape
Data=df.iloc[0 : row , 0 : (col-1)]
Label=df.iloc[0 : row , (col-1)]

In [11]:
Data

         0  0.64  0.64.1  0.1  0.32  ...   0.43   0.44  3.756   61   278
0     0.21  0.28    0.50  0.0  0.14  ...  0.180  0.048  5.114  101  1028
1     0.06  0.00    0.71  0.0  1.23  ...  0.184  0.010  9.821  485  2259
2     0.00  0.00    0.00  0.0  0.63  ...  0.000  0.000  3.537   40   191
3     0.00  0.00    0.00  0.0  0.63  ...  0.000  0.000  3.537   40   191
4     0.00  0.00    0.00  0.0  1.85  ...  0.000  0.000  3.000   15    54
...    ...   ...     ...  ...   ...  ...    ...    ...    ...  ...   ...
4595  0.31  0.00    0.62  0.0  0.00  ...  0.000  0.000  1.142    3    88
4596  0.00  0.00    0.00  0.0  0.00  ...  0.000  0.000  1.555    4    14
4597  0.30  0.00    0.30  0.0  0.00  ...  0.000  0.000  1.404    6   118
4598  0.96  0.00    0.00  0.0  0.32  ...  0.000  0.000  1.147    5    78
4599  0.00  0.00    0.65  0.0  0.00  ...  0.000  0.000  1.250    5    40

[4600 rows x 57 columns]

In [12]:
Label

0       1
1       1
2       1
3       1
4       1
       ..
4595    0
4596    0
4597    0
4598    0
4599    0
Name: 1, Length: 4600, dtype: int64

In [13]:
Label.value_counts()

0    2788
1    1812
Name: 1, dtype: int64

In [17]:
from sklearn.model_selection import train_test_split
from sklearn.cluster import KMeans

X=Data
y=Label

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20,random_state=42)

kmns=KMeans(n_clusters=2, random_state=0)
kmns.fit(X_train,y_train)

KMeans(n_clusters=2, random_state=0)

In [18]:
predictions = kmns.predict(X_test)
print(predictions)

[0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0
 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]

In [19]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, predictions)

0.5956521739130435

In [20]:
df=pd.read_csv('/heart_failure_clinical_records_dataset.csv')

In [21]:
[row,col]=df.shape
Data=df.iloc[0 : row , 0 : (col-1)]
Label=df.iloc[0 : row , (col-1)]

In [22]:
from sklearn.model_selection import train_test_split
from sklearn.cluster import KMeans

X=Data
y=Label

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20,random_state=42)

kmns=KMeans(n_clusters=2, random_state=0)
kmns.fit(X_train,y_train)

KMeans(n_clusters=2, random_state=0)

In [23]:
predictions = kmns.predict(X_test)
print(predictions)

[0 1 1 1 0 0 0 1 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 1 1
 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 1 1 0 0 0 0 0 0]

In [24]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, predictions)

0.5833333333333334